### ISSUE TITLE
Versión de Ubuntu

### ISSUE THREAD

**Issue by kcifuentes** [joselfonseca/docker-nginx-php-73#2]
Hola Jose, hasta el momento he seguido todos tus videos y livecoding, solo tengo una pregunta con respecto a este repositorio, y es si tienes pensado actualizar la versión de Ubuntu para esta imagen, ya que tengo pensado usarla para una aplicación que estoy desarrollando y el cliente me solicita que se use la última versión estable de Sistema Operativo en mención. Gracias de antemano por tu respuesta.

**Comment by joselfonseca** [comment]
Hola, tengo pensado actualizar a `18.04` la próxima semana después de unos demos que tengo de algunas apps.

**Comment by joselfonseca** [comment]
https://github.com/joselfonseca/docker-nginx-php-74-dev
https://github.com/joselfonseca/docker-nginx-php-74

Nuevas imágenes con PHP 7.4 y Ubuntu 20.04
